# Generated by Django 6.0.6 on 2026-06-13 09:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('download', models.IntegerField()),
                ('Genre', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('download_link', models.URLField(default='')),
                ('date_release', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('game_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.game')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.userprofile')),
            ],
        ),
    ]
