# Generated by Django 6.0.6 on 2026-06-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0002_remove_comment_user_name_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_img',
            field=models.ImageField(default='default.jpg', upload_to='game_img/'),
        ),
    ]
